# Generated by Django 2.0.3 on 2020-01-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.IntegerField(choices=[(0, 'Injured'), (1, 'Questionable'), (2, 'Probable'), (3, 'Out'), (4, 'PUP'), (5, 'Suspended'), (6, 'Active')], default=6),
        ),
    ]
