# Generated by Django 2.0.3 on 2020-01-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20200118_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.IntegerField(choices=[(0, 'QB'), (1, 'RB'), (2, 'FB'), (3, 'WR'), (4, 'TE'), (5, 'C'), (6, 'LG'), (7, 'LT'), (8, 'RG'), (9, 'RT'), (10, 'LDT'), (11, 'LDE'), (12, 'RDT'), (13, 'RDE'), (14, 'WLB'), (15, 'MLB'), (16, 'SLB'), (17, 'LCB'), (18, 'RCB'), (19, 'FS'), (20, 'SS'), (21, 'PK'), (22, 'P'), (23, 'H'), (24, 'PR'), (25, 'KR'), (26, 'LS')], default=0),
        ),
    ]
