# Generated by Django 2.0.3 on 2020-01-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20200118_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameteam',
            name='positionChoice',
            field=models.IntegerField(choices=[(0, 'QB'), (1, 'RB1'), (2, 'RB2'), (3, 'WR1'), (4, 'WR2'), (5, 'TE'), (6, 'DEF'), (7, 'FLEX')], default=0),
        ),
    ]
