# Generated by Django 2.0.3 on 2020-01-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20200121_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='playerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fanPts', models.DecimalField(decimal_places=2, max_digits=6)),
                ('projPts', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pctStart', models.IntegerField(default=0)),
                ('passYds', models.IntegerField(default=0)),
                ('passTD', models.IntegerField(default=0)),
                ('passInt', models.IntegerField(default=0)),
                ('rushAtts', models.IntegerField(default=0)),
                ('rushYds', models.IntegerField(default=0)),
                ('rushTD', models.IntegerField(default=0)),
                ('recvTgt', models.IntegerField(default=0)),
                ('recvRec', models.IntegerField(default=0)),
                ('recvYds', models.IntegerField(default=0)),
                ('recvTD', models.IntegerField(default=0)),
                ('retnYds', models.IntegerField(default=0)),
                ('retnTD', models.IntegerField(default=0)),
                ('twoPT', models.IntegerField(default=0)),
                ('fumTot', models.IntegerField(default=0)),
                ('funLpst', models.IntegerField(default=0)),
                ('playerInfo', models.ManyToManyField(blank=True, related_name='stats', to='teams.player')),
            ],
        ),
    ]
