# Generated by Django 2.0.3 on 2020-01-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20200129_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='fanPts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='projPts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
