# Generated by Django 2.0.3 on 2020-02-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20200129_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstats',
            old_name='rushAtts',
            new_name='passAtts',
        ),
    ]
