# Generated by Django 2.0.3 on 2020-02-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_auto_20200201_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='playerInfo',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='playerId',
            field=models.IntegerField(default=0),
        ),
    ]
