# Generated by Django 2.0.3 on 2020-02-01 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20200201_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstats',
            old_name='passAtts',
            new_name='rushAtts',
        ),
    ]
