# Generated by Django 2.0.3 on 2020-02-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_auto_20200201_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='defStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fanPts', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('projPts', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pctStart', models.IntegerField(default=0)),
                ('ptsVsTackles', models.IntegerField(default=0)),
                ('sack', models.IntegerField(default=0)),
                ('safe', models.IntegerField(default=0)),
                ('ints', models.IntegerField(default=0)),
                ('funRec', models.IntegerField(default=0)),
                ('TD', models.IntegerField(default=0)),
                ('blkKick', models.IntegerField(default=0)),
                ('retnYds', models.IntegerField(default=0)),
                ('retnTD', models.IntegerField(default=0)),
                ('playerId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='kickerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fanPts', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('projPts', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pctStart', models.IntegerField(default=0)),
                ('under20', models.IntegerField(default=0)),
                ('under30', models.IntegerField(default=0)),
                ('under40', models.IntegerField(default=0)),
                ('under50', models.IntegerField(default=0)),
                ('over50', models.IntegerField(default=0)),
                ('made', models.IntegerField(default=0)),
                ('playerId', models.IntegerField(default=0)),
            ],
        ),
    ]
