# Generated by Django 2.0.3 on 2020-02-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_defstats_kickerstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defstats',
            old_name='ptsVsTackles',
            new_name='ptsAll',
        ),
    ]
