# Generated by Django 2.0.3 on 2020-02-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_auto_20200202_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defstats',
            old_name='funRec',
            new_name='fumRec',
        ),
    ]
