# Generated by Django 2.0.3 on 2020-02-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_auto_20200202_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defstats',
            name='sack',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
