# Generated by Django 2.0.3 on 2020-02-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0022_seasonschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonschedule',
            name='day',
            field=models.IntegerField(choices=[(0, 'Thursday'), (1, 'Saturday'), (2, 'Sunday'), (3, 'Monday')], default=2),
        ),
        migrations.AlterField(
            model_name='seasonschedule',
            name='week',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, 'Wild Card'), (19, 'Divisional'), (20, 'Conference'), (21, 'Super Bowl')], default=1),
        ),
    ]
