# Generated by Django 2.0.3 on 2020-02-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0025_auto_20200211_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameteam',
            name='positionChoice',
            field=models.IntegerField(choices=[(0, 'QB'), (1, 'RB1'), (2, 'RB2'), (3, 'WR1'), (4, 'WR2'), (5, 'TE'), (6, 'DEF'), (7, 'FLEX'), (8, 'K')], default=0),
        ),
    ]
