# Generated by Django 2.0.3 on 2020-02-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0026_auto_20200212_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='weeklyRankings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('teamId', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('ranking', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='gameteam',
            name='ranking',
        ),
        migrations.AddField(
            model_name='gameteam',
            name='pts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
