# Generated by Django 2.0.3 on 2020-03-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0027_auto_20200226_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameteam',
            name='week',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, 'Wild Card'), (19, 'Divisional'), (20, 'Conference'), (21, 'Super Bowl')], default=1),
        ),
    ]
